package gen

import (
	"fmt"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"strings"

	"github.com/dave/jennifer/jen"
	"github.com/go-git/go-billy/v5/util"
	"github.com/korylprince/go-adm/schema"
	"github.com/korylprince/go-adm/utils/git"
	"github.com/korylprince/go-adm/utils/replace"
)

type EncodeOption func(*Encoder)

func WithReplacements(reps replace.Replacements) EncodeOption {
	return func(e *Encoder) {
		e.reps = reps
	}
}

func WithSchemaEncoderOption(opt schema.EncodeOption) EncodeOption {
	return func(e *Encoder) {
		e.sOpts = append(e.sOpts, opt)
	}
}

type Encoder struct {
	f     *jen.File
	reps  replace.Replacements
	enc   *schema.Encoder
	sOpts []schema.EncodeOption
}

func NewEncoder(f *jen.File, opts ...EncodeOption) *Encoder {
	e := &Encoder{f: f, sOpts: []schema.EncodeOption{}}
	for _, opt := range opts {
		opt(e)
	}
	e.sOpts = append(e.sOpts, schema.WithReplacements(e.reps))
	e.enc = schema.NewEncoder(f, e.sOpts...)
	return e
}

func (e *Encoder) Encode(file *schema.File) {
	e.enc.RegisterFile(file)

	for _, typ := range file.Types {
		switch t := typ.(type) {
		case *schema.Enum:
			e.enc.EncodeEnum(t)
		case *schema.Struct:
			e.enc.EncodeStruct(t)
		}
	}
}

func GenerateFromFiles(fileNames []string, pkg string, reps replace.Replacements, tags []string, out io.Writer, opts ...EncodeOption) error {
	var schemas []*schema.Schema
	var baseFileNames []string
	for _, fileName := range fileNames {
		buf, err := os.ReadFile(fileName)
		if err != nil {
			return fmt.Errorf("could not read %s: %w", fileName, err)
		}
		s, err := schema.New(buf)
		if err != nil {
			return fmt.Errorf("could not parse %s: %w", fileName, err)
		}
		schemas = append(schemas, s)
		baseFileNames = append(baseFileNames, filepath.Base(fileName))
	}

	f := jen.NewFile(pkg)

	f.HeaderComment(`Code generated by "` + filepath.Base(os.Args[0]) + `"; DO NOT EDIT.`)
	srcStr := "Source"
	if len(fileNames) > 1 {
		srcStr += "s"
	}
	f.HeaderComment(srcStr + ": " + strings.Join(baseFileNames, ", "))

	file := schema.NewFile(schemas)
	opts = append([]EncodeOption{WithReplacements(reps), WithSchemaEncoderOption(schema.WithTags(tags))}, opts...)
	NewEncoder(f, opts...).Encode(file)
	if err := f.Render(out); err != nil {
		return fmt.Errorf("could not render code: %w", err)
	}

	return nil
}

func GenerateFromGit(repoURL, commit, path, pkg string, reps replace.Replacements, tags []string, out io.Writer, opts ...EncodeOption) error {
	repo, err := git.New(repoURL, commit)
	if err != nil {
		return fmt.Errorf("could not check out repository: %w", err)
	}

	hash, err := repo.Hash()
	if err != nil {
		return fmt.Errorf("could not get hash: %w", err)
	}

	var schemas []*schema.Schema
	if err = util.Walk(repo, path, func(filePath string, info fs.FileInfo, _ error) error {
		if !strings.HasSuffix(info.Name(), ".yaml") {
			return nil
		}

		buf, err := util.ReadFile(repo, filePath)
		if err != nil {
			return fmt.Errorf("could not read %s: %w", filePath, err)
		}

		s, err := schema.New(buf)
		if err != nil {
			return fmt.Errorf("could not parse %s: %w", filePath, err)
		}
		schemas = append(schemas, s)

		return nil
	}); err != nil {
		return err
	}

	f := jen.NewFile(pkg)
	f.HeaderComment("DO NOT EDIT")
	f.HeaderComment(fmt.Sprintf("generated from %s:%s/%s", repoURL, hash, path))

	file := schema.NewFile(schemas)
	opts = append([]EncodeOption{WithReplacements(reps), WithSchemaEncoderOption(schema.WithTags(tags))}, opts...)
	NewEncoder(f, opts...).Encode(file)
	if err := f.Render(out); err != nil {
		return fmt.Errorf("could not render code: %w", err)
	}

	return nil
}
