// DO NOT EDIT
// generated from https://github.com/apple/device-management.git:f878dea98fb88293a3686e44bcfb891f8e78f98f/declarative/declarations

package declarations

const DeviceManagementGenerateHash = "f878dea98fb88293a3686e44bcfb891f8e78f98f"

var DeclarationMap = map[string]any{"any": DeclarationBase{}}

// Keys common to all declarations used with the Remote Management protocol.
type DeclarationBase struct {
	// A string specifying the type of this declaration.
	Type string `json:"Type" plist:"Type" required:"true"`
	// A string uniquely identifying this declaration. The size of this string should not exceed 64 octets. A UUID string value is a good choice.
	Identifier string `json:"Identifier" plist:"Identifier" required:"true"`
	// A unique token generated by the server specifying a particular revision of the declaration. The size of this string should not exceed 64 octets.
	ServerToken string `json:"ServerToken" plist:"ServerToken" required:"true"`
	// The payload describing this declaration.
	Payload Payload `json:"Payload" plist:"Payload" required:"true"`
}

func (p *DeclarationBase) DeclarationType() string {
	return "any"
}

// The payload describing this declaration.
type Payload struct{}
